services:
- mongodb

language: node_js
node_js:
    - "4"
    - "6"
before_script:
    - npm install
script:
- npm test

notifications:
  email:
    - lah_spfc2010@hotmail.com
    - isnack.yagami@gmail.com